### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by jinnycho503** [norangi/voxel_text_editor#1]
### Render texts on the screen
- [ ] Create a `Node` container that signifies a node containing necessary information.
- [ ] Create doubly linked list data structures (`DoublyLinkedList` container)
    - [ ] Which by default adds empty space `Node` in the end
- [ ] Make sure that linked lists work as expected
- [ ] Create a `Wrapper` container that contains multiple `DoublyLinkedList`s
- [ ] Make sure that all the received inputs are contained in these data structures above data structure☝️

### Other input handlings
- [ ] Newlines
- [ ] Arrows
- [ ] Backspaces
- [ ] Wordwrapping
- [ ] Cursors
- [ ] Vertical scrolls
- [ ] Undo and redo
- [ ] Pretty cursors and scrolls (transparent, etc)
 
- [ ] Create a wrapper that takes these

**Comment by norangi** [comment]
<img width="878" alt="screen shot 2018-05-05 at 10 37 05 pm" src="https://user-images.githubusercontent.com/36755736/40402614-becd9788-5e1a-11e8-9846-103cf2aa8081.png">
![Uploading Screen Shot 2018-05-05 at 10.38.30 PM.png…]()

**Comment by jinnycho503** [comment]
## More advanced rendering
- [ ] I might enable the link to url (like markdown)
- [ ] Something specific about graphics visualization

**Comment by norangi** [comment]
<img width="534" alt="screen shot 2018-05-28 at 6 37 57 pm" src="https://user-images.githubusercontent.com/36755736/40631029-4b696c64-62a6-11e8-87a2-9cda1eeef31e.png">

**Comment by norangi** [comment]
```javascript
const outerL = [[1,2,3],[4,5,6],[7,8,9]];
outerL.map(function (innerL) {
    innerL.map(function (element) {
        console.log(element);
    });
    console.log('----');
});
```
Returns:
```
1
2
3
----
4
5
6
----
7
8
9
----
```
